name: elia

packages:
  - ./

scripts:
  analyze:
    exec: flutter analyze

  format:
    exec: dart format --set-exit-if-changed

  test:
    exec: flutter test

  generate:
    description: generate code
    exec: dart run build_runner build --delete-conflicting-outputs
